### ISSUE TITLE
pry-nav does not work with the latest version of pry

### ISSUE THREAD

**Issue by cdhagmann** [nixme/pry-nav#35]
Bundler could not find compatible versions for gem "pry":
  In Gemfile:
    pry (~> 0.13.1)

    pry-nav was resolved to 0.3.0, which depends on
      pry (>= 0.9.10, < 0.13.0)

**Comment by iloveitaly** [comment]
@cdhagmann this is fixed on master, give it a try and let me know what you think! We'll release a new version via rubygems soon.

**Comment by makikata** [comment]
@iloveitaly thank you I use it daily and it works like a charm!!!

I do not know which one of the repository below should I create an issue, thus commenting here as it is related. Otherwise please advise.

Based on [this comment](https://github.com/deivid-rodriguez/pry-byebug/issues/33#issuecomment-833968151), it seems that the pry-byebug fork works with pry-remote. However it looks like combining below, breaks pry-nav.

- https://gitlab.com/gitlab-org/gitlab-pry-byebug/-/tree/release_new_version 
- nixme/pry-nav (master)
- pry-remote

**Comment by iloveitaly** [comment]
@makikata are you on MRI ruby or another ruby runtime?

**Comment by makikata** [comment]
@iloveitaly I am on MRI 3.0.1

**Comment by iloveitaly** [comment]
Closing this out
